Screen:

    MDRectangleFlatButton:
        text: "Light Button"
        pos_hint: {'center_x': 0.5, 'center_y': 0.8}
        md_bg_color: app.theme_cls.primary_light

    MDRaisedButton:
        text: "Light Button"
        pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        md_bg_color: app.theme_cls.primary_light

    MDRaisedButton:
        text: "Primary Button"
        pos_hint: {'center_x': 0.5, 'center_y': 0.4}

    MDRaisedButton:
        text: "Dark Button"
        pos_hint: {'center_x': 0.5, 'center_y': 0.2}
        md_bg_color: app.theme_cls.primary_dark

    # Go to https://github.com/kivymd/KivyMD/tree/master/kivymd/uix/button for more buttons
    # Visit https://github.com/kivymd/KivyMD/blob/master/kivymd/color_definitions.py for more KivyMD colors
