BoxLayout:
    orientation:'vertical'
    MDToolbar:
        title: "Bottom Nvabar"
        md_bg_color: .2, .2, .2, 1

        # specific_text_color: 1, 0, 0,1 to change text color

    MDBottomNavigation:
        #panel_color: 0, 0, 0, 1 to change the panel color

        MDBottomNavigationItem:
            name: 'screen 1'
            text: "python"
            icon: "language-python"
            # For more MDIcons Visit http://zavoloklom.github.io/material-design-iconic-font/icons.html

            MDLabel:
                text: 'Python'
                halign: "center"

        MDBottomNavigationItem:
            name: 'screen 2'
            text: "youtube"
            icon: "youtube"

            MDLabel:
                text: 'Youtube'
                halign: "center"

        MDBottomNavigationItem:
            name: 'screen 3'
            text: "instagram"
            icon: "instagram"

            MDLabel:
                text: 'Instagram'
                halign: "center"
